# -*- coding: utf-8 -*-
{
    'name': 'Bleaching Dept',
    'sequence': 0,
    'author': 'Ateeq Ur Rehman',
    'version': '0.0.0.2',
    'category': 'Production Planning',
    'summary': 'PPC ERP Module',
    'description': """PPC ERP Module""",
    'depends': ['base', 'mail', 'web', 'web_notify'],
    'data': [
        'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/security/ir.model.access.csv',
        'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/security/bleaching_security.xml',
        'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/views/bleaching_dept.xml',
        'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/views/machine_types.xml',
        'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/views/bleaching_machines.xml',
        # 'C:/Edraak/Odoo main/odoo project 2/custom_modules/bleaching_dept/views/issuance_form.xml',
    ],
    'demo': [],
    'application':True,
    'installable': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'bleaching_dept/static/src/create_internal_plan/js/create_internal_plan.js',
            'bleaching_dept/static/src/create_internal_plan/xml/create_internal_plan.xml',
            'bleaching_dept/static/src/create_internal_plan/css/create_internal_plan.css',
            'bleaching_dept/static/src/order_selction_for_internal_plan/js/order_selction_for_internal_plan.js',
            'bleaching_dept/static/src/order_selction_for_internal_plan/xml/order_selction_for_internal_plan.xml',
            'bleaching_dept/static/src/order_selction_for_internal_plan/css/order_selction_for_internal_plan.css',
            'bleaching_dept/static/src/machine_route/js/machine_route.js',
            'bleaching_dept/static/src/machine_route/xml/machine_route.xml',
            'bleaching_dept/static/src/machine_route/css/machine_route.css',
            'bleaching_dept/static/src/machine_params_recipes/js/machine_params.js',
            'bleaching_dept/static/src/machine_params_recipes/xml/machine_params.xml',
            'bleaching_dept/static/src/bleacing_machine_status/js/bleacing_machine_status.js',
            'bleaching_dept/static/src/bleacing_machine_status/xml/bleacing_machine_status.xml',
            'bleaching_dept/static/src/bleacing_machine_status/css/bleaching_machine_status.css',
            'bleaching_dept/static/src/params_selector/js/params_selector.js',
            'bleaching_dept/static/src/params_selector/xml/params_selector.xml',
            'bleaching_dept/static/src/machine_params_recipes/css/machine_params.css',
            'bleaching_dept/static/src/params_selector/css/params_selector.css',
            'bleaching_dept/static/src/order_details/js/order_details.js',
            'bleaching_dept/static/src/order_details/xml/order_details.xml',
            'bleaching_dept/static/src/order_details/css/order_details.css',
            'bleaching_dept/static/src/supervisor/order_receiving_screen/js/order_receiving.js',
            'bleaching_dept/static/src/supervisor/order_receiving_screen/xml/order_receiving.xml',
            'bleaching_dept/static/src/supervisor/order_receiving_screen/css/order_receiving_screen.css',
            'bleaching_dept/static/src/reprocess_orders/js/reprocess_orders.js',
            'bleaching_dept/static/src/reprocess_orders/xml/reprocess_orders.xml',
            'bleaching_dept/static/src/production_coplete_orders/js/production_complete_orders.js',
            'bleaching_dept/static/src/production_coplete_orders/xml/production_complete_orders.xml',
        ],
    },
    'license': 'LGPL-3'
}
